// HybridMatiksRealtime.hpp — C++ implementation of the MatiksRealtime HybridObject.
//
// Implements the nitrogen-generated spec `HybridMatiksRealtimeSpec`. The single
// async method decrypts AES-256-CBC question blobs on a background std::thread and
// resolves a Promise back on the JS thread via Nitro's CallInvoker — the off-thread
// pattern from repo doc 02-architecture-and-performance/12-native-infrastructure.md §3.
#pragma once

// Generated by `npx nitrogen` into nitrogen/generated/shared/c++/.
// That dir is added to the include path by the generated +autolinking.cmake (Android)
// and +autolinking.rb (iOS), so a bare include resolves it.
#include "HybridMatiksRealtimeSpec.hpp"

#include <memory>
#include <string>
#include <vector>

#include <NitroModules/Promise.hpp>

namespace margelo::nitro::matiksrealtime {

using namespace facebook;

class HybridMatiksRealtime : public HybridMatiksRealtimeSpec {
 public:
  // Nitro requires a default constructor; it forwards TAG to the HybridObject base.
  HybridMatiksRealtime() : HybridObject(TAG) {}

  // From the generated spec:
  //   virtual std::shared_ptr<Promise<std::vector<std::string>>>
  //   decryptQuestions(const std::vector<std::string>& blobs,
  //                    const std::string& keyUtf8) = 0;
  std::shared_ptr<Promise<std::vector<std::string>>> decryptQuestions(
      const std::vector<std::string>& blobs,
      const std::string& keyUtf8) override;
};

} // namespace margelo::nitro::matiksrealtime
