#include <jni.h>
#include <fbjni/fbjni.h>
#include "MatiksRealtimeOnLoad.hpp" // generated by `npx nitrogen` (nitrogen/generated/android/)

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
  return facebook::jni::initialize(vm, []() {
    margelo::nitro::matiksrealtime::registerAllNatives();
  });
}
